### ISSUE TITLE
Taffybar install unclear and perhaps new dependencies

### ISSUE THREAD

**Issue by JPustkuchen** [simlu/xmonad#10]
1. See https://ubuntu.pkgs.org/16.04/ubuntu-universe-amd64/taffybar_0.4.5-4build2_amd64.deb.html
=> New dependencies?

> sudo dpkg -i taffybar_0.4.5-4build2_amd64.deb     Vormals nicht ausgewähltes Paket taffybar wird gewählt.
> (Lese Datenbank ... 61344 Dateien und Verzeichnisse sind derzeit installiert.)
> Vorbereitung zum Entpacken von taffybar_0.4.5-4build2_amd64.deb ...
> Entpacken von taffybar (0.4.5-4build2) ...
> dpkg: Abhängigkeitsprobleme verhindern Konfiguration von taffybar:
>  taffybar hängt ab von libatk1.0-0 (>= 1.12.4); aber:
>   Paket libatk1.0-0 ist nicht installiert.
>  taffybar hängt ab von libcairo2 (>= 1.2.4); aber:
>   Paket libcairo2 ist nicht installiert.
>  taffybar hängt ab von libfontconfig1 (>= 2.9.0); aber:
>   Paket libfontconfig1 ist nicht installiert.
>  taffybar hängt ab von libgdk-pixbuf2.0-0 (>= 2.22.0); aber:
>   Paket libgdk-pixbuf2.0-0 ist nicht installiert.
>  taffybar hängt ab von libgtk2.0-0 (>= 2.24.0); aber:
>   Paket libgtk2.0-0 ist nicht installiert.
>  taffybar hängt ab von libpango-1.0-0 (>= 1.14.0); aber:
>   Paket libpango-1.0-0 ist nicht installiert.
>  taffybar hängt ab von libpangocairo-1.0-0 (>= 1.14.0); aber:
>   Paket libpangocairo-1.0-0 ist nicht installiert.
>  taffybar hängt ab von libpangoft2-1.0-0 (>= 1.14.0); aber:
>   Paket libpangoft2-1.0-0 ist nicht installiert.
> 
> dpkg: Fehler beim Bearbeiten des Paketes taffybar (--install):
>  Abhängigkeitsprobleme - verbleibt unkonfiguriert
> Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
> Fehler traten auf beim Bearbeiten von:
>  taffybar

2. Your description misses the wget which seems to be required to fetch the .deb file first before installing it?

3. sudo apt-get taffybar requires ~1GB ?!

**Comment by JPustkuchen** [comment]
1 + 3 is solved. It was da local problem.

2 could still need some love :)

**Comment by simlu** [comment]
Fyi Ubuntu 18.04 is due for release very soon (end of month). I'll go through the entire guide in detail using that version once that is the case.

**Comment by simlu** [comment]
Going over this again. Taffybar will be kicked out. Please re-open as adequate
